services:
  timescaledb:
    container_name: meteo_timescaledb
    image: timescale/timescaledb:2.25.0-pg17
    environment:
      POSTGRES_USER: infoclimat
      POSTGRES_PASSWORD: infoclimat2026
      POSTGRES_DB: meteodb
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
      - ./timescaledb-env/meteodb_dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - bd_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U infoclimat -d meteodb"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 40s
    restart: unless-stopped

  nginx:
    container_name: meteo_nginx
    image: nginx:1.29.5-alpine3.23-perl
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_net

  backend:
    container_name: meteo_backend
    build:
      context: ./backend
    env_file:
      - ./.env
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - app_net
      - bd_net

  frontend:
    container_name: meteo_frontend
    build:
      context: ./frontend
    env_file:
      - ./.env
    networks:
      - app_net

  prometheus:
    container_name: meteo_prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app_net
      - monitoring

  grafana:
    container_name: meteo_grafana
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secure_password
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  timescaledb-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-storage:
    driver: local

networks:
  app_net:
  bd_net:
  monitoring:
